### ISSUE TITLE
Trip events not in chronological order

### ISSUE THREAD

**Issue by nkansal96** [thenathanyang/tripify#43]
## Issue

Events are not displayed in chronological order on the View Trip page:

<img width="512" alt="screen shot 2018-11-30 at 1 04 30 am" src="https://user-images.githubusercontent.com/3259309/49279308-fece9780-f43b-11e8-808a-0846641f97fc.png">

## Fix

Sort the events

**Comment by quigg-caroline** [comment]
I tried to fix this in a previous pr, did it not work? : 

https://github.com/thenathanyang/tripify/commit/9e6f12b5e25ab23e0ec335d6734427c3cc722deb#diff-e874fe9d4cf6160413cbb377a6655629

**Comment by nkansal96** [comment]
The `sort` comparator needs to return an integer, not a boolean. I fixed this in #49
